namespace ET
{
	/// <summary>
	/// 当前协议的版本号
	/// </summary>
	public enum TCPCmdProtocolVer { VerSign = 20140624 };
    
    /// <summary>
    /// 用户命令
    /// </summary>
    public enum TCPLoginServerCmds { CMD_LOGIN_ON1 = 1, CMD_LOGIN_ON2 = 20 };

    /// <summary>
    /// 用户命令
    /// </summary>
    public enum TCPGameServerCmds
    {
        CMD_LOGIN_ON1 = 1,
        CMD_LOGIN_ON2 = 20,
        CMD_NTF_CMD_BASE_ID = 21,
        CMD_LOG_OUT = 22,
        CMD_SPR_CLIENTHEART = 23,
        CMD_PREREMOVE_ROLE = 98, // 增加预删除角色消息
        CMD_UNREMOVE_ROLE = 99, // 恢复预删除的角色
        CMD_LOGIN_ON = 100,
        CMD_ROLE_LIST, CMD_CREATE_ROLE, CMD_REMOVE_ROLE,
        CMD_INIT_GAME, CMD_SYNC_TIME, CMD_PLAY_GAME, CMD_SPR_MOVE, CMD_SPR_MOVEEND, CMD_SPR_MOVE2,
        CMD_OTHER_ROLE, CMD_OTHER_ROLE_DATA, CMD_SPR_POSITION, CMD_SPR_PETPOS, CMD_SPR_ACTTION, CMD_SPR_ACTTION2,
        CMD_SPR_MAGICCODE, CMD_SPR_ATTACK, CMD_SPR_INJURE,
        CMD_SPR_REALIVE, CMD_SPR_RELIFE, CMD_SPR_CLICKON, CMD_SYSTEM_MONSTER,
        CMD_SPR_MAPCHANGE, CMD_LOG_OUT_Unused_Dont_Del, CMD_SPR_NEWTASK, CMD_SPR_GETATTRIB2,
        CMD_SPR_LEAVE, CMD_SPR_NPC_BUY, CMD_SPR_NPC_SALEOUT, CMD_SPR_ADD_GOODS, CMD_SPR_MOD_GOODS,
        CMD_SPR_MERGE_GOODS, CMD_SPR_SPLIT_GOODS, CMD_SPR_GET_MERGETYPES, CMD_SPR_GET_MERGEITEMS, CMD_SPR_GET_MERGENEWGOODS,
        CMD_SPR_CHGCODE, CMD_SPR_MONEYCHANGE, CMD_SPR_MODTASK, CMD_SPR_COMPTASK, CMD_SPR_EXPCHANGE,
        CMD_SPR_GETFRIENDS, CMD_SPR_ADDFRIEND, CMD_SPR_REMOVEFRIEND,
        CMD_SPR_NEWGOODSPACK, CMD_SPR_DELGOODSPACK, CMD_SPR_CLICKONGOODSPACK,
        CMD_SPR_GETTHING, CMD_SPR_CHGPKMODE, CMD_SPR_CHGPKVAL, CMD_SPR_UPDATENPCSTATE, CMD_SPR_NPCSTATELIST, CMD_SPR_GETNEWTASKDATA,
        CMD_SPR_ABANDONTASK, CMD_SPR_HITED, CMD_SPR_MODKEYS, CMD_SPR_CHAT,
        CMD_SPR_USEGOODS, CMD_SPR_CHANGEPOS, CMD_SPR_NOTIFYCHGMAP, CMD_SPR_FORGE, CMD_SPR_ENCHANCE,
        CMD_SPR_GETOTHERATTRIB, CMD_SPR_UPDATE_ROLEDATA, CMD_SPR_REMOVE_COOLDOWN,
        CMD_SPR_MALL_BUY, CMD_SPR_YINLIANG_BUY, CMD_SPR_USERMONEYCHANGE, CMD_SPR_USERYINLIANGCHANGE, CMD_SPR_GOODSEXCHANGE, CMD_SPR_EXCHANGEDATA,
        CMD_SPR_MOVEGOODSDATA, CMD_SPR_GOODSSTALL, CMD_SPR_STALLDATA, CMD_SPR_STALLNAME,
        CMD_SPR_TEAM, CMD_SPR_TEAMDATA, CMD_SPR_TEAMID, CMD_SPR_BATTLE, CMD_SPR_NPCSCRIPT,
        CMD_SPR_DEAD, CMD_SPR_AUTOFIGHT, CMD_SPR_HORSE, CMD_SPR_PET,
        CMD_SPR_DIANJIANGLIST, CMD_SPR_DIANJIANGDATA, CMD_SPR_DJROOMROLESDATA, CMD_SPR_DIANJIANG, CMD_SPR_DIANJIANGFIGHT,
        CMD_SPR_DIANJIANGPOINT, CMD_SPR_GETDJPOINTS, CMD_SPR_UPDATEINTERPOWER,
        CMD_SPR_GOTOMAP, CMD_SPR_NOTIFYMSG, CMD_SPR_QUERYIDBYNAME, CMD_ADDHORSE, CMD_ADDPET, CMD_GETHORSELIST, CMD_GETOTHERHORSELIST, CMD_GETPETLIST,
        CMD_MODHORSE, CMD_MODPET, CMD_SELECTHORSE, CMD_GETGOODSLISTBYSITE, CMD_GETLINEINFO, CMD_GETJINGMAILIST, CMD_UP_JINGMAI_LEVEL,
        CMD_GETOTHERJINGMAILIST, CMD_SPR_LOADALREADY, CMD_SPR_BULLETINMSG, CMD_SPR_GMAUTH, CMD_SPR_EQUIPUPGRADE, CMD_SPR_ENCHASEJEWEL,
        CMD_SPR_SHOWBIGUAN, CMD_SPR_GETBIGUAN, CMD_SPR_UPSKILLLEVEL, CMD_SPR_ADD_SKILL, CMD_SPR_JINGMAI_INFO, CMD_SPR_HORSEENCHANCE,
        CMD_SPR_HORSEUPGRADE, CMD_SPR_SALEGOODS, CMD_SPR_SELFSALEGOODSLIST, CMD_SPR_OTHERSALEGOODSLIST, CMD_SPR_MARKETROLELIST,
        CMD_SPR_MARKETGOODSLIST, CMD_SPR_MARKETBUYGOODS, CMD_SPR_MODDEFSKILLID, CMD_SPR_MODAUTODRINK, CMD_SPR_PLAYDECO, CMD_SPR_BUFFERDATA,
        CMD_SPR_RUNTOMAP, CMD_SPR_SEARCHROLES, CMD_SPR_LISTROLES, CMD_SPR_LISTTEAMS, CMD_SPR_RESETBAG, CMD_SPR_DAILYTASKDATA, CMD_SPR_DAILYJINGMAIDATA,
        CMD_SPR_CHGNUMSKILLID, CMD_SPR_GETSKILLUSEDNUM, CMD_SPR_CHGHORSEBODY, CMD_SPR_PORTABLEBAGDATA, CMD_SPR_RESETPORTABLEBAG,
        CMD_SPR_EXECWABAO, CMD_SPR_GETWABAODATA, CMD_SPR_GETHUODONGDATA, CMD_SPR_GETWLOGINGIFT, CMD_SPR_GETNEWSTEPGIFT, CMD_SPR_GETMTIMEGIFT,
        CMD_SPR_GETBIGGIFT, CMD_SPR_GETSONGLIGIFT, CMD_SPR_CHGHUODONGID, CMD_SPR_FUBENDATA, CMD_SPR_ENTERFUBEN, CMD_SPR_NOTIFYENTERFUBEN,
        CMD_SPR_CLIENTHEART_OLD, CMD_SPR_OHTERJINGMAIEXP, CMD_GETRANDOMNAME, CMD_SKILLUSEDNUMFULL, CMD_SPR_GETFUBENHISTDATA, CMD_SPR_GETFUBENBEGININFO,
        CMD_SPR_COPYMAPMONSTERSNUM, CMD_SPR_FINDMONSTER, CMD_SPR_BATCHYINPIAO, CMD_SPR_FORCETOLAOFANG, CMD_SPR_CHGPURPLENAME, CMD_SPR_CHGLIANZHAN,
        CMD_SPR_GETROLEDAILYDATA, CMD_SPR_GETBOSSINFODICT, CMD_SPR_GETPAIHANGLIST, CMD_SPR_YABIAODATA, CMD_SPR_STARTYABIAO, CMD_SPR_ENDYABIAO,
        CMD_SPR_YABIAOTAKEGOODS, CMD_SPR_TOUBAO, CMD_SPR_GETOTHERATTRIB2, CMD_SPR_NEWBIAOCHE, CMD_SPR_DELBIAOCHE, CMD_SPR_FINDBIAOCHE,
        CMD_SPR_CHGBIAOCHELIFEV, CMD_SPR_NOTIFYENDCHONGXUE, CMD_SPR_ADDHORSELUCKY, CMD_SPR_BATTLEKILLEDNUM, CMD_SPR_CHGBATTLENAMEINFO,
        CMD_SPR_NOFITYPOPUPWIN, CMD_SPR_NOTIFYBATTLEROLEINFO, CMD_SPR_NOTIFYBATTLEENDINFO, CMD_SPR_GETCHONGZHIJIFEN, CMD_SPR_NOTIFYTEAMCHGLEVEL,
        CMD_SPR_GETFUBENHISTLISTDATA, CMD_SPR_CHGHEROINDEX, CMD_GETOTHERHORSEDATA, CMD_UPDATEALLTHINGINDEXS, CMD_SPR_CHGHALFYINLIANGPERIOD,
        CMD_SPR_GETBANGHUILIST, CMD_SPR_CREATEBANGHUI, CMD_SPR_CHGBANGHUIINFO, CMD_SPR_QUERYBANGHUIDETAIL, CMD_SPR_UPDATEBANGHUIBULLETIN,
        CMD_SPR_GETBHMEMBERDATALIST, CMD_SPR_UPDATEBHVERIFY, CMD_SPR_APPLYTOBHMEMBER, CMD_SPR_ADDBHMEMBER, CMD_SPR_REMOVEBHMEMBER,
        CMD_SPR_QUITFROMBANGHUI, CMD_SPR_DESTROYBANGHUI, CMD_SPR_BANGHUIVERIFY, CMD_SPR_INVITETOBANGHUI, CMD_SPR_CHGBHMEMBERZHIWU,
        CMD_SPR_CHGBHMEMBERCHENGHAO, CMD_SPR_SEARCHROLESFROMDB, CMD_SPR_AGREETOTOBANGHUI, CMD_SPR_REFUSEAPPLYTOBH, CMD_SPR_GETBANGGONGHIST,
        CMD_SPR_DONATEBGMONEY, CMD_SPR_DONATEBGGOODS, CMD_SPR_BANGGONGCHANGE, CMD_SPR_GETBANGQIINFO, CMD_SPR_RENAMEBANGQI, CMD_SPR_UPLEVELBANGQI,
        CMD_SPR_CHGJUNQILIFEV, CMD_SPR_NEWJUNQI, CMD_SPR_DELJUNQI, CMD_SPR_LINGDIFORBH, CMD_SPR_CHGHUANGDIROLEID, CMD_SPR_GETBHLINGDIINFODICTBYBHID,
        CMD_SPR_SETLINGDITAX, CMD_SPR_TAKELINGDITAXMONEY, CMD_SPR_GETHUANGDIBHINFO, CMD_SPR_NOTIFYBHZHIWU, CMD_SPR_OPENYANGGONGBK, CMD_SPR_REFRESHYANGGONGBK,
        CMD_SPR_CLICKYANGGONGBK, CMD_SPR_REFRESHQIZHENGE, CMD_SPR_QIZHEGEBUY, CMD_SPR_QUERYQIZHEGEBUYHIST, CMD_SPR_QUICKJINGMAI, CMD_SPR_QUICKHORSEENCHANCE,
        CMD_SPR_QUICKEQUIPENHANCE, CMD_SPR_QUICKEQUIPFORGE, CMD_SPR_GETHUANGDIROLEDATA, CMD_SPR_ADDHUANGFEI, CMD_SPR_REMOVEHUANGFEI, CMD_SPR_GETHUANGFEIDATA,
        CMD_SPR_SENDTOLAOFANG, CMD_SPR_TAKEOUTLAOFANG, CMD_SPR_BANCHAT, CMD_SPR_CHGHUANGHOU, CMD_SPR_GETLINGDIMAPINFO, CMD_SPR_GETHUANGCHENGMAPINFO,
        CMD_SPR_ADDLINGDITAXMONEY, CMD_SPR_INVITEADDHUANGFEI, CMD_SPR_AGREEADDHUANGFEI, CMD_SPR_TASKTRANSPORT, CMD_SPT_LINGLIGUANZHU, CMD_SPR_GETGOODSBYDBID,
        CMD_SPR_QUICKCOMPLETETASK, CMD_SPR_QUERYCHONGZHIMONEY, CMD_SPR_GETFIRSTCHONGZHIDALI, CMD_SPR_NOTIFYBATTLESIDE, CMD_SPR_NOTIFYBATTLEAWARD, CMD_SPR_EXECWABAOBYYAOSHI,
        CMD_SPR_SUBFORGE, CMD_SPR_GETUSERMAILLIST, CMD_SPR_GETUSERMAILDATA, CMD_SPR_FETCHMAILGOODS, CMD_SPR_DELETEUSERMAIL, CMD_SPR_GETMAILSENDCODE,
        CMD_SPR_SENDUSERMAIL, CMD_SPR_RECEIVELASTMAIL, CMD_SPR_EQUIPBORNINDEXUPDATE, CMD_SPR_EQUIPINHERIT, CMD_SPR_QUERYINPUTFANLI,
        CMD_SPR_QUERYINPUTJIASONG, CMD_SPR_QUERYINPUTKING, CMD_SPR_QUERYLEVELKING, CMD_SPR_QUERYEQUIPKING, CMD_SPR_QUERYHORSEKING, CMD_SPR_QUERYJINGMAIKING,
        CMD_SPR_QUERYAWARDHIST, CMD_SPR_EXECUTEINPUTFANLI, CMD_SPR_EXECUTEINPUTJIASONG, CMD_SPR_EXECUTEINPUTKING, CMD_SPR_EXECUTELEVELKING, CMD_SPR_EXECUTEEQUIPKING,
        CMD_SPR_EXECUTEHORSEKING, CMD_SPR_EXECUTEJINGMAIKING, CMD_SPR_MALLZHENQIBUY, CMD_SPR_FETCHACTIVITYAWARD, CMD_SPR_VIPDAILYDATA, CMD_SPR_USEVIPDAILYPRIORITY,
        CMD_SPR_ACTIVITYTRANSPORT, CMD_SPR_YANGGONGBKDAILYDATA, CMD_SPR_FETCHYANGGONGBKJIFENAWARD, CMD_SPR_QUERYSHILIANTAAWARDINFO, CMD_SPR_FETCHSHILIANTAAWARD,
        CMD_SPR_COMPLETETINYCLIENT, CMD_SPR_USERGOLDCHANGE, CMD_SPR_NOTIFYSHENGXIAOGUESSSTAT, CMD_SPR_NOTIFYSHENGXIAOGUESSRESULT, CMD_SPR_ADDSHENGXIAOMORTGAGE,
        CMD_SPR_QUERYROLESHENGXIAOGUESSLIST, CMD_SPR_QUERYSHENGXIAOGUESSHISTORY, CMD_SPR_QUERYSHENGXIAORECENTRESULTLIST, CMD_SPR_QUERYSHENGXIAOGUESSSELFHISTORY,
        CMD_SPR_UPDATETENGXUNFCMRATE, CMD_SPR_NEWNPC, CMD_SPR_DELNPC, CMD_SPR_EXTGRIDBYYUANBAO, CMD_SPR_SUBMONEY, CMD_SPR_EXTBAGNUMBYYUANBAO, CMD_SPR_STOPMOVE,
        CMD_SPR_NOTIFYEQUIPSTRONG,
        CMD_SPR_EXCUTENPCLUATALK, CMD_SPR_EXCUTENPCLUAFUNCTION, CMD_SPR_ARENABATTLE, CMD_SPR_ARENABATTLEKILLEDNUM, CMD_SPR_CITYWARREQUEST, CMD_SPR_TAKELINGDIDAILYAWARD,
        CMD_SPR_NOTIFYOPENWINDOW, CMD_SPR_CHENGJIUDATA, CMD_SPR_FETCHCHENGJIUAWARD, CMD_SPR_DSHIDECMD, CMD_SPR_NEWDECO, CMD_SPR_DELDECO, CMD_SPR_MENDEQUIPMENT,
        CMD_SPR_NOTIFYGOODSINFO, CMD_SPR_ROLEPARAMSCHANGE, CMD_SPR_EQUIPFENJIE, CMD_SPR_JINGYUANEXCHANGE, CMD_SPR_HUIZHANGEXCHANGE, CMD_SPR_ACTIVATNEXTLEVELJINGMAI,
        CMD_SPR_FETCHVIPONCEAWARD, CMD_SPR_TASKTRANSPORT2, CMD_SPR_ACTIVATNEXTLEVELWUXUE, CMD_SPR_CAIJI, CMD_SPR_RUNTASKPLOTLUA,
        CMD_SPR_PLAYGAMEEFFECT, CMD_SPR_TRANSFERSOMETHING, CMD_SPR_CHANGEPETAITYPE, CMD_SPR_FETCHMALLDATA, CMD_SPR_MALLQIANGGOUBUYGOODS,
        CMD_SPR_FETCHZUANHUANGAWARD, CMD_SPR_SETSYSTEMOPENPARAMS, CMD_SPR_ENTERTASKFUBEN, CMD_SPR_GETUPLEVELGIFTOK, CMD_SPR_UPDATEWEIGHTS,
        CMD_SPR_GETTASKAWARDS, CMD_SPR_NOTIFYGETGOODSPACK, CMD_SPR_RESETJINDANBAG, CMD_SPR_GETJINDANGOODSLIST, CMD_SPR_ZAJINDAN, CMD_SPR_QUERYZAJINDANHISTORY,
        CMD_SPR_QUERYSELFZAJINDANHISTORY, CMD_SPR_GETWANGCHENGMAPINFO, CMD_SPR_GETLIMITTIMELOGINGIFT, CMD_SPR_ROLESTATUSCMD, CMD_SPR_GETTO60AWARD, CMD_SPR_GETKAIFUONLINEINFO,
        CMD_SPR_GETDAYCHONGZHIDALI, CMD_SPR_GETJIERIXMLDATA, CMD_SPR_QUERYJIERIDALIBAO, CMD_SPR_QUERYJIERIDENGLU, CMD_SPR_QUERYJIERIVIP, CMD_SPR_QUERYJIERICZSONG, CMD_SPR_QUERYJIERICZLEIJI,
        CMD_SPR_QUERYJIERIZIKA, CMD_SPR_QUERYJIERIXIAOFEIKING, CMD_SPR_QUERYJIERICZKING, CMD_SPR_EXECUTEJIERIDALIBAO, CMD_SPR_EXECUTEJIERIDENGLU, CMD_SPR_EXECUTEJIERIVIP, CMD_SPR_EXECUTEJIERICZSONG, CMD_SPR_EXECUTEJIERICZLEIJI,
        CMD_SPR_EXECUTEJIERIZIKA, CMD_SPR_EXECUTEJIERIXIAOFEIKING, CMD_SPR_EXECUTEJIERICZKING, CMD_SPR_CHGJIERICHENGHAO, CMD_SPR_FACTIVITIESDATA, CMD_SPR_YUANBAOCOMPLETETASK,
        CMD_SPR_QUERYHEFUDALIBAO, CMD_SPR_QUERYHEFUVIP, CMD_SPR_QUERYHEFUCZSONG, CMD_SPR_QUERYHEFUFANLI, CMD_SPR_QUERYHEFUPKKING, CMD_SPR_QUERYHEFUWCKING, CMD_SPR_QUERYXINFANLI,
        CMD_SPR_EXECUHEFUDALIBAO, CMD_SPR_EXECUHEFUVIP, CMD_SPR_EXECUHEFUCZSONG, CMD_SPR_EXECUHEFUFANLI, CMD_SPR_EXECUHEFUPKKING, CMD_SPR_EXECUHEFUWCKING, CMD_SPR_EXECUXINFANLI,
        CMD_SPR_ONEKEYQUICKSALEOUT, CMD_SPR_ACTIVATNEXTLEVELZHANHUN, CMD_SPR_ACTIVATNEXTLEVELRONGYU, CMD_SPR_ACTIVATRONGYUBUFFER, CMD_SPR_LIANLUJINGLIAN, CMD_SPR_ZJDJIFEN,
        CMD_SPR_FETCHZJDJIFENAWARD,
        CMD_SPR_QUERYACTIVITYINFO,  // 客户端请求活动的相关信息 -- 比如冲级豪礼名额 神装领取名额 幸运抽奖次数[7/18/2013 LiaoWei]
        CMD_SPR_XINGYUNCHOUJIANG,   // 幸运抽奖 [7/18/2013 LiaoWei]
        CMD_SPR_QUERYYUEDUCHOUJIANGHISTORY,         // 客户端请求月度抽奖历史(全服玩家)[7/23/2013 LiaoWei]
        CMD_SPR_QUERYSELFQUERYYUEDUCHOUJIANGHISTORY,// 客户端请求月度抽奖历史(玩家自己) [7/23/2013 LiaoWei]
        CMD_SPR_EXECUTEYUEDUCHOUJIANG,              // 客户端点击月度抽奖 [7/23/2013 LiaoWei]
        CMD_SPR_QUERYYUEDUCHOUJIANGINFO,            // 客户端请求月度抽奖信息--能玩的次数和活动期间充值的元宝数 [7/23/2013 LiaoWei]
        CMD_SPR_EXECUTEHUNQIEXCHANGE,               // 客户端发起魂器卖出操作 [8/7/2013 LiaoWei]
        CMD_SPR_EXECUTECHANGEOCCUPATION,            // 客户端发起转职操作  [9/28/2013 LiaoWei]
        CMD_SPR_EXECUTECHANGELIFE,                  // 客户端发起转生操作  [9/28/2013 LiaoWei]
        CMD_SPR_BEGINBLINK,                         // 闪现开始 [10/28/2013 LiaoWei]
        CMD_SPR_ENDBLINK,                           // 闪现结束 [10/28/2013 LiaoWei]
        CMD_SPR_GETROLEUSINGGOODSDATALIST,
        CMD_SPR_EXECUTEPROPADDPOINT,                // 属性加点 [10/31/2013 LiaoWei]
        CMD_SPR_EXECUTERECOMMENDPROPADDPOINT,       // 推荐属性加点 [10/31/2013 LiaoWei]
        CMD_SPR_EXECUTERECLEANPROPADDPOINT,         // 清除属性加点 [10/31/2013 LiaoWei]
        CMD_SPR_QUERYCLEANPROPADDPOINT,             // 请求清除属性加点信息 [2/11/2014 LiaoWei]
        CMD_SPR_BLOODCASTLEBEGINFIGHT,              // 血色堡垒开始战斗 -- 客户端把桥头的阻挡去掉 [11/7/2013 LiaoWei]
        CMD_SPR_BLOODCASTLEKILLMONSTERAHASDONE,     // 血色堡垒断桥怪击杀到达限额 -- 客户端把桥尾的阻挡去掉 [11/7/2013 LiaoWei]
        CMD_SPR_BLOODCASTLEENDFIGHT,                // 血色堡垒结束战斗 -- 客户端显示倒计时界面 [11/7/2013 LiaoWei]
        CMD_SPR_FUBENCLEANOUT,                      // 副本扫荡 [11/15/2013 LiaoWei]
        CMD_SPR_FUBENPASSNOTIFY,                    // 副本通关通告 [11/15/2013 LiaoWei]
        CMD_SPR_QUERYFUBENINFO,                    // 客户端请求副本信息 [11/15/2013 LiaoWei]
        CMD_SPR_ATTACK2,                           // 2号攻击请求 针对于黑龙波等特殊技能 [11/22/2013 LiaoWei]
        CMD_SPR_COMPLETEFLASHSCENE,                // 完成新手场景 [11/30/2013 LiaoWei]
        CMD_SPR_FRESHPLAYERSCENEKILLMONSTERAHASDONE,// 新手场景断桥怪击杀到达限额 -- 客户端把桥尾的阻挡去掉 [12/1/2013 LiaoWei]
        CMD_SPR_REFURBISHTASKSTARLEVEL,             // 客户端刷新任务星级 [12/3/2013 LiaoWei]
        CMD_SPR_COMPLETEDAILYCIRCLETASKFORONCECLICK,// 一键完成日常跑环任务 [12/5/2013 LiaoWei]
        CMD_SPR_ADMIREDPLAYER,                      // 客户端点击崇拜某人的操作 [12/10/2013 LiaoWei]
        CMD_SPR_QUERYBLOODCASTLEINFO,               // 请求血色堡垒基本信息 [12/14/2013 LiaoWei]
        CMD_SPR_EQUIPAPPENDPROP,                    // 装备追加消息 [12/18/2013 LiaoWei]
        CMD_SPR_BLOODCASTLEPREPAREFIGHT,            // 血色堡垒准备战斗 -- 客户端显示战斗倒计时 [12/20/2013 LiaoWei]
        CMD_SPR_BLOODCASTLECOMBATPOINT,             // 血色堡垒战斗积分 -- 客户端显示战斗积分 [12/20/2013 LiaoWei]
        CMD_SPR_BLOODCASTLEKILLMONSTERSTATUS,       // 血色堡垒杀怪状态 -- 客户端显示杀怪的状态 [12/20/2013 LiaoWei]
        CMD_SPR_QUERYCAMPBATTLEINFO,                // 请求阵营战场基本信息 [12/23/2013 LiaoWei]
        CMD_SPR_QUERYDAIMONSQUAREINFO,              // 请求恶魔广场基本信息 [12/25/2013 LiaoWei]
        CMD_SPR_QUERYDAIMONSQUARETIMERINFO,         // 恶魔广场时间信息 [12/25/2013 LiaoWei]
        CMD_SPR_QUERYDAIMONSQUAREMONSTERWAVEANDPOINTRINFO,// 恶魔广场怪物和得分信息 [12/25/2013 LiaoWei]
        CMD_SPR_DAIMONSQUAREENDFIGHT,                // 恶魔广场结束 [12/25/2013 LiaoWei]
        CMD_SPR_UPDATEEVERYDAYONLINEAWARDGIFTINFO,    // 更新玩家的每日在线信息 [1/12/2014 LiaoWei]
        CMD_SPR_GETEVERYDAYONLINEAWARDGIFT,          // 领取每日在线奖励 [1/12/2014 LiaoWei]
        CMD_SPR_UPDATEEVERYDAYSERIESLOGININFO,      // 更新玩家的连续登陆信息 [1/12/2014 LiaoWei]
        CMD_SPR_GETEVERYDAYSERIESLOGINAWARDGIFT,    // 领取连续登陆奖励 [1/12/2014 LiaoWei]
        CMD_SPR_FRESHPLAYERSCENEOVERTIME,           // 新手场景超时 通知客户端 [1/16/2014 LiaoWei]
        CMD_SPR_UPDATEGETTHINGSFLAG,                // 更新拾取设置
        CMD_SPR_BLOODCASTLEPLAYERNUMNOTIFY,         // 血色堡垒人数通知 [1/20/2014 LiaoWei]
        CMD_SPR_DAIMONSQUAREPLAYERNUMNOTIFY,        // 恶魔广场人数通知 [1/20/2014 LiaoWei]
        CMD_SPR_BATTLEPLAYERNUMNOTIFY,              // 阵营战人数通知  [1/20/2014 LiaoWei]
        CMD_SPR_EXCHANGEMOJINGANDQIFU,              // 魔晶和祈福兑换 [1/23/2014 LiaoWei]
        CMD_SPR_GETMEDITATEEXP,                     // 获取冥想经验 [1/24/2014 LiaoWei]
        CMD_SPR_GETMEDITATETIMEINFO,                // 获取冥想时间信息 [1/24/2014 LiaoWei]
        CMD_SPR_QUERYTOTALLOGININFO,                // 请求累计登陆数据 [2/11/2014 LiaoWei]
        CMD_SPR_GETTOTALLOGINAWARD,                 // 领取累计登陆奖励 [2/11/2014 LiaoWei]
        CMD_SPR_CHANGELIFEFOREQUIP,                 // 客户端装备转生操作 [2/15/2014 LiaoWei]
        CMD_SPR_FLAKEOFFCHANGELIFEFOREQUIP,         // 客户端装备转生剥离操作 [2/15/2014 LiaoWei]
        CMD_SPR_ONEKEYFINDFRIEND,                   // 点击一键征友 [2/15/2014 LiaoWei]
        CMD_SPR_ONEKEYADDFRIEND,                    // 点击一键加友 [2/15/2014 LiaoWei]
        CMD_SPR_GETVIPAWARD,                        // 获得VIP奖励 [2/20/2014 LiaoWei]
        CMD_SPR_DAILYACTIVEDATA,                    // 获取每日活跃信息 [2/25/2014 LiaoWei]
        CMD_SPR_GETDAILYACTIVEAWARD,                // 获取每日活跃奖励 [2/25/2014 LiaoWei]
        CMD_SPR_SETAUTOASSIGNPROPERTYPOINT,         // 设置自动分配点设置 [3/3/2014 LiaoWei]
        CMD_SPR_GETBLOODCASTLEAWARD,                // 领取血色堡垒的奖励 [3/8/2014 LiaoWei]
        CMD_SPR_GETDAIMONSQUAREAWARD,               // 领取恶魔广场的奖励 [3/8/2014 LiaoWei]
        CMD_SPR_GETCOPYMAPAWARD,                    // 领取副本奖励 [3/5/2014 LiaoWei]
        CMD_SPR_GETSKILLINFO,                       // 客户端请求技能信息 [3/17/2014 LiaoWei]
        CMD_SPR_EXPERIENCECOPYMAPINFO,              // 经验副本信息 [3/18/2014 LiaoWei]
        CMD_SPR_ZHANMENGSHIJIAN_DETAIL,             // 战盟事件详情 [3/14/2014 JinJieLong]
        CMD_SPR_KAIFUACTIVITYINFO,                  // 开服活动信息 [3/20/2014 LiaoWei]
        CMD_SPR_GETTHEKINGOFPKINFO,                 // 请求PK之王基本信息 [3/22/2014 LiaoWei]
        CMD_SPR_NOTIFYTHEKINGOFPKAWARDINFO,         // PK之王奖励信息 [3/22/2014 LiaoWei]
        CMD_SPR_ANGELTEMPLETIMERINFO,               // 天使神殿时间信息(准备战斗、开始战斗、结束战斗) [12/20/2013 LiaoWei]
        CMD_SPR_ANGELTEMPLEFIGHTEND,                // 天使神殿结束--显示奖励[12/20/2013 LiaoWei]
        CMD_SPR_ANGELTEMPLEFIGHTINFOALL,            // 天使神殿战斗信息--群发 [3/23/2014 LiaoWei]
        CMD_SPR_ANGELTEMPLEFIGHTINFOSINGLE,         // 天使神殿战斗信息--给自己 [3/23/2014 LiaoWei]
        CMD_SPR_ANGELTEMPLESPARK,                   // 天使神殿战力鼓舞 [3/23/2014 LiaoWei]
        CMD_SPR_GETANGELTEMPLEBASEINFO,             // 天使神殿基本信息[3/23/2014 LiaoWei]
        CMD_SPR_QUERYADRATIONPKKINGINFO,            // 请求PK之王崇拜信息[3/23/2014 LiaoWei]
        CMD_SPR_ADRATIONPKKING,                     // PK之王崇拜[3/23/2014 LiaoWei]
        CMD_SPR_JINGJI_DETAIL,                      // 竞技场详情 [3/24/2014 JinJieLong]   
        CMD_SPR_JINGJI_REQUEST_CHALLENGE,           // 竞技场请求挑战 [3/24/2014 JinJieLong]
        CMD_SPR_JINGJI_CHALLENGE_END,               // 竞技场挑战结束弹出奖励窗口[3/24/2014 JinJieLong]
        CMD_SPR_JINGJI_NOTIFY_START,                // 竞技场通知开始倒计时
        CMD_SPR_JINGJI_CHALLENGEINFO,                // 竞技场战报[3/25/2014 JinJieLong]
        CMD_SPR_JINGJI_RANKING_REWARD,              // 竞技场领取排行榜奖励[3/25/2014 JinJieLong]
        CMD_SPR_JINGJICHANG_REMOVE_CD,              // 竞技场消除挑战CD [3/25/2014 JinJieLong]
        CMD_SPR_JINGJICHANG_GET_BUFF,               // 竞技场领取Buff [3/25/2014 JinJieLong]
        CMD_SPR_JINGJICHANG_JUNXIAN_LEVELUP,        // 竞技场升级军衔 [3/25/2014 JinJieLong]
        CMD_SPR_JINGJICHANG_LEAVE,                  // 离开竞技场消息[3/29/2014 JinJieLong]
        CMD_SPR_CHGFAKEROLELIFEV,                   //假人的血量修改
        CMD_SPR_NEWFAKEROLE,                        //新假人通知
        CMD_SPR_DELFAKEROLE,                        //删除假人
        CMD_SPR_OPENMARKET,                         //打开交易市场
        CMD_SPR_MARKETSALEMONEY,                    //交易市场中上架金币
        CMD_SPR_GETVIPINFO,                         // 玩家请求VIP信息 [3/28/2014 LiaoWei]
        CMD_SPR_GETVIPLEVELAWARD,                   // 玩家领取VIP等级奖励 [3/28/2014 LiaoWei]
        CMD_SPR_VIPLEVELUP,                         // 玩家VIP等级升级 [3/28/2014 LiaoWei]
        CMD_SPR_GETLIXIANBAITANTICKS,               // 获取离线摆摊时长(毫秒)
        CMD_SPR_UPDATELIXIANBAITANTICKS,            // 修改离线摆摊时长(毫秒)
        CMD_SPR_QUERYOPENGRIDTICK,                  // 请求开背包格子时间戳 [4/7/2014 LiaoWei]
        CMD_SPR_QUERYOPENPORTABLEGRIDTICK,          // 请求开随身仓库包裹的时间戳 [4/7/2014 LiaoWei]
        CMD_SPR_STARTMEDITATE,                      // 开始冥想
        CMD_SPR_ZHANMENGBUILDUPLEVEL,               // 战盟建筑升级
        CMD_SPR_ZHANMENGBUILDGETBUFFER,             // 领取战盟建筑的buffer
        CMD_SPR_GETBAITANLOG,                       // 获取摆摊日志
        CMD_SPR_GETPUSHMESSAGEINFO,                 // 客户端把推送信息发给服务器[4/23/2014 LiaoWei]
        CMD_SPR_ACTIVATIONPICTUREJUDGE,             // 激活图鉴 [5/3/2014 LiaoWei]
        CMD_SPR_GETNPICTUREJUDGEINFO,               // 取得图鉴信息 [5/3/2014 LiaoWei]
        CMD_SPR_MUEQUIPUPGRADE,                     // 装备进阶 [4/30/2014 LiaoWei]
        CMD_SPR_WINGUPSTAR,                         // 翅膀升星 [5/4/2014 liuhuicheng]
        CMD_SPR_WINGUPGRADE,                        // 翅膀进阶 [5/4/2014 liuhuicheng]
        CMD_SPR_WINGOFFON,                          // 翅膀佩戴/卸载 [5/4/2014 liuhuicheng]
        CMD_SPR_CHECK,                              // 与服务器心跳，每两秒发一次，校验是否加速
        CMD_SPR_REFERPICTUREJUDGE,                  // 提交图鉴信息 [5/17/2014 LiaoWei]
        CMD_SPR_GETMOJINGEXCHANGEINFO,              // 客户端请求魔晶钻石兑换信息 [5/21/2014 LiaoWei]
        CMD_SPR_REFRESH_ICON_STATE,                 // 刷新图标状态信息 [5/21/2014 ChenXiaojun]
        CMD_SPR_EQUIPAPPENDINHERIT,                 // 追加传承 [5/24/2014 LiaoWei]
        CMD_SPR_SWEEP_WANMOTA,                      // 扫荡万魔塔 [6/5/2014 ChenXiaojun]
        CMD_SPR_UPDATE_SWEEP_STATE,                 // 更新扫荡状态 [6/5/2014 ChenXiaojun]
        CMD_SPR_GET_WANMOTA_DETAIL,                 // 获取万魔塔信息 [6/5/2014 ChenXiaojun]
        CMD_SPR_GET_SWEEP_REWARD,                   // 领取扫荡奖励 [6/5/2014 ChenXiaojun]
        CMD_SPR_LISTCOPYTEAMS,                      // 搜索副本队伍 [6/5/2014 LiTeng]
        CMD_SPR_COPYTEAM,                           // 副本组队命令 [6/5/2014 LiTeng]
        CMD_SPR_COPYTEAMDATA,                       // 副本队伍信息 [6/5/2014 LiTeng]
        CMD_SPR_COPYTEAMSTATE,                      // 副本队伍成员状态变更 [6/5/2014 LiTeng]
        CMD_SPR_REGEVENTNOTIFY,                     // 注册事件通知(副本组队) [6/5/2014 LiTeng]
        CMD_SPR_LISTCOPYTEAMDATA,                   // 队伍列表中的队伍信息变化 [6/5/2014 LiTeng]
        CMD_SPR_COPYTEAMDAMAGEINFO,                 // 队伍成员伤害信息 [6/6/2014 LiTeng]
        CMD_SPR_GOLDCOPYSCENEPREPAREFIGHT,          // 金币副本准备战斗 -- 客户端显示战斗倒计时 [6/11/2014 LiaoWei]
        CMD_SPR_GOLDCOPYSCENEMONSTERWAVE,           // 金币副本刷怪波数 [6/11/2014 LiaoWei]
        CMD_SPR_GETNEWZONEACTIVEAWARD,              // 获取新区活动奖 [6/10/2014 gwz]
        CMD_SPR_QUERYUPLEVELMADMAN,                 // 冲级狂人 [6/10/2014 gwz]
        CMD_SPR_QUERYNEWZONEACTIVE,                 // 新区活动 [6/10/2014 gwz]
        CMD_SPR_QUERYUPLEVELGIFTINFO,               // 请求等级奖励领取信息 [6/16/2014 LiTeng]
        CMD_SPR_GETUPLEVELGIFTAWARD,                // 领取等级奖励奖励 [6/16/2014 LiTeng]
        CMD_SPR_JINGJI_START_FIGHT,                 // 竞技场战斗开始消息[6/17/2014 ChenXiaojun]
        CMD_SPR_QUERY_REPAYACTIVEINFO,              // 查询回馈活动信息 [6/17/2014 gwz]
        CMD_SPR_GET_REPAYACTIVEAWARD,               // 获取回馈活动奖励 [6/17/2014 gwz]
        CMD_SPR_QUERY_ALLREPAYACTIVEINFO,           // 获取所有回馈信息，充值和消费值 [6/19/2014 gwz]
        CMD_SPR_QUERYACTIVITYSOMEINFO,              // 请求活动(血色城堡、恶魔广场)的一些信息 [7/8/2014 LiaoWei]
        //CMD_SPR_DESTROYGOODS,                     //摧毁物品
        CMD_SPR_PLAYBOSSANIMATION,                  //boss出生前通知播放动画
        CMD_SPR_ENDBOSSANIMATION,                   //客户端通知服务器端开始刷新boss（防止外挂，参数有校验）
        CMD_SPR_QUERY_TODAYCANDOINFO,               //查询今日可做 [7/9/2014 gwz]
        CMD_SPR_QUERY_GETOLDRESINFO,                //查询资源找回信息 [7/9/2014 gwz]
        CMD_SPR_GET_OLDRESOURCE,                    //资源找回，领取资源 [7/9/2014 gwz]
        CMD_SPR_EXTENSIONPROPSHITED,                //拓展属性命中通知
        CMD_SPR_EXEC_WASHPROPS,                     //执行装备洗练
        CMD_SPR_EXEC_WASHPROPSINHERIT,              //执行装备洗练传承
        CMD_SPR_BATTLE_SCORE_LIST,                  //阵营战积分排名信息 [7/23/2014 lt]
        CMD_SPR_STORYCOPYMAPINFO,                   // 剧情副本信息 [7/24/2014 LiaoWei]
        CMD_SPR_GETUSERMAILCOUNT,                   //获取邮件数量 [7/28/2014 lt]
        CMD_SPR_QUERYIMPETRATEINFO,                 // 请求祈福数据 [7/30/2014 LiaoWei]
        CMD_SPR_EXECUTEIMPETRATE,                   // 执行祈福 [7/30/2014 LiaoWei]
        CMD_SPR_OPENMARKET2,                        //打开交易市场 MU交易所功能修改的第二套交易类指令开始
        CMD_SPR_MARKETSALEMONEY2,                   //交易市场中上架金币
        CMD_SPR_SALEGOODS2,
        CMD_SPR_SELFSALEGOODSLIST2,
        CMD_SPR_OTHERSALEGOODSLIST2,
        CMD_SPR_MARKETROLELIST2,
        CMD_SPR_MARKETGOODSLIST2,
        CMD_SPR_MARKETBUYGOODS2,                    //MU交易所功能修改的第二套交易类指令结束
        CMD_SPR_QUERYSTARCONSTELLATIONINFO,         // 请求星座数据 [8/1/2014 LiaoWei]
        CMD_SPR_EXECUTEACTIVATIONSTARCONSTELLATION, // 激活星座 [8/1/2014 LiaoWei]
        CMD_SPR_CHANGEANGLE, // 修改角色的360角度


        CMD_SPR_UPDATESHARESTATE,                   // 处理分享[8/6/2014 gwz]
        CMD_SPR_GETSHAREAWARD,                      // 发放分享奖励[8/6/2014 gwz]
        CMD_SPR_GETSHARESTATE,                      //获取分享状态
        CMD_SPR_BROADSPECIALHINTTEXT,               // 播放特殊的提示信息，例如boss AI描述
        CMD_SPR_MAPAIEVENT,                         // 发送地图事件，例如清除光幕
        CMD_SPR_EXEC_LIANZHI,                       // 执行炼制
        CMD_SPR_QUERY_LIANZHICOUNT,                 // 查询炼制次数
        CMD_SPR_UPGRADE_CHENGJIU,                   // 提升成就 [9/15/2014 ChenXiaojun]
        CMD_SPR_GETFIRSTCHARGEINFO,                 //获得各个充值档首次充值信息
        CMD_SPR_BATCHFETCHMAILGOODS,                //批量提取邮件
        CMD_SPR_PUSH_VERSION,                       //报告客户端代码版本号
        CMD_SPR_NOTIFYTEAMCHGZHANLI,                 //通知组队队员战力变化
        CMD_SPR_NOTIFYSELFCHGZHANLI,                 //通知自己战力变化
        CMD_SPR_NOTIFYOTHERBUFFERDATA,               //通知他人Buff变化变化
        CMD_SPR_NOTIFYSHOWGONGGAO,                   //登录后获取公告显示信息 [10/28/2014 ChenXiaojun]
        CMD_SPR_GETWINGINFO,                        //获取翅膀信息
        CMD_SPR_EMOLAIXIMONSTERINFO,                //恶魔来袭副本怪物数信息 [11/18/2014 LiTeng]
        CMD_SPR_CAIJI_START,                        //开始采集
        CMD_SPR_CAIJI_FINISH,                       //完成采集
        CMD_SPR_CAIJI_LASTNUM,                      //水晶幻境采集剩余次数
        CMD_SPR_QUERYJIERITOTALCONSUME,
        CMD_SPR_EXECUTEJIERITOTALCONSUME,
		CMD_MAP_TELEPORT,                           //地图传送点状态列表
		CMD_SPR_SPECIALMACHINE,                     // 是否特殊的机器
        CMD_SPR_EXTRADATA,                          // 报告特殊信息
        
		// 避免Client和GameServer、GameServer和GameDBServer之间协议号出错的问题
        // 从1.3.0开始，协议号都要自己制定枚举值！！！！！
        CMD_SPR_GE = 699,
        CMD_SPR_CHENGZHAN_JINGJIA = 700,            //罗兰城战竞价进攻方资格
        CMD_SPR_GET_CHENGZHAN_DAILY_AWARD = 701,    //罗兰城战胜利战盟成员领取每日奖励
        CMD_SPR_LUOLANCHENGZHAN = 702,              //罗兰城战进入指令
        CMD_SPR_LUOLANCHENGZHAN_LONGTA_ROLEINFO = 703,    //罗兰城战龙塔内人数信息列表
        CMD_SPR_LUOLANCHENGZHAN_QIZHI_OWNERINFO = 704,    //罗兰城战旗帜拥有者列表
        CMD_SPR_LUOLANCHENGZHAN_LONGTA_OWNERINFO = 705,   //龙塔占有者信息
        CMD_SPR_GET_LUOLANCHENGZHU_INFO = 706,              //获取罗兰城主战盟信息
        CMD_SPR_LUOLANCHENGZHAN_RESULT_INFO = 707,         //罗兰城战结果和奖励信息
        CMD_SPR_GET_LUOLANCHENGZHAN_REQUEST_INFO_LIST = 708, //请求帮会领地信息，主要用来获取竞价信息
        CMD_SPR_SERVERUPDATE_ZHANMENGZIJIN = 709,         //服务器发送战盟当前资金信息
        CMD_SPR_MODIFY_FASHION = 710,                       //使用和卸下时装
        CMD_SPR_GETBANGHUIFUBEN = 711,                    // 取得帮会副本的信息
        CMD_SPR_GETBANGHUIFUBENAWARD = 712,               // 取得帮会副本的奖励

        CMD_SPR_GET_ELEMENTHRT_SLIST = 720,               //申请元素数据
        CMD_SPR_GET_ELEMENTHRTS_INFO = 721,               //申请获取猎取元素相关信息,
        CMD_SPR_USE_ELEMENTHRT = 722,                     //佩戴/卸下元素之心
        CMD_SPR_GET_SOMEELEMENTHRTS = 723,                //执行猎取操作
        CMD_SPR_POWER_ELEMENTHRT = 724,                   //强化元素之心
        CMD_SPR_RESET_EHRTSBAG = 725,                    //整理背包
        CMD_SPR_GET_USINGELEMENTHRT_SLIST = 726,          //申请元素装备栏数据

        CMD_SPR_HOLD_QINGGONGYAN = 730,                   // 申请举办庆功宴
        CMD_SPR_GET_QINGGONGYAN = 731,                    // 申请庆功宴信息
        CMD_SPR_JOIN_QINGGONGYAN = 732,                   // 申请参加庆功宴
        CMD_SPR_IFQINGGONGYANOPEN = 733,                  // 当前是否开启了庆功宴

        CMD_SPR_GETDAMONGOODSLIST = 740,                  //精灵系统获取备战的精灵列表  
        CMD_SPR_GET_PET_LIST = 750,                       // 申请精灵背包数据
        CMD_SPR_GET_PET_INFO = 751,                       // 申请召唤精灵界面信息
        CMD_SPR_CALL_PET = 752,                           // 请求精灵召唤
        CMD_SPR_MOVE_PET = 753,                           // 从精灵背包中拿出精灵
        CMD_SPR_RESET_PETBAG = 754,                       // 整理精灵背包
                    
        CMD_SPR_FAZHEN_BOSS =760,                         //罗兰法阵BOSS信息
        CMD_SPR_GET_STORE_YINLIANG = 761,                 // 取得仓库金币
        CMD_SPR_GET_STORE_MONEY = 762,                    // 取得仓库绑定金币
        CMD_SPR_STORE_YINLIANG_CHANGE = 763,              // 通知客户端仓库金币改变
        CMD_SPR_STORE_MONEY_CHANGE = 764,                 // 通知客户端仓库绑定金币改变

        CMD_SPR_JIERIACT_STATE = 770,                       // 通知客户端节日活动开启或结束
        //节日活动修改方案
        CMD_SPR_GETJIERIFANBEI_INFO = 771,                  // 客户端请求节日活动翻倍的类型

        CMD_SPR_ACHIEVEMENT_RUNE_INFO = 780,                 //成就符文——提升信息
        CMD_SPR_ACHIEVEMENT_RUNE_UP = 781,                   //成就符文——提升
        CMD_SPR_PRESTIGE_MEDAL_INFO = 782,                   // 声望勋章信息
        CMD_SPR_PRESTIGE_MEDAL_UP = 783,                     // 勋章属性提升
		
        CMD_SPR_ARTIFACT_UP = 791,                        //神器再造
        
		CMD_SPR_GET_LINGYU_LIST = 800,                      // 查看翎羽信息
        CMD_SPR_ADVANCE_LINGYU_LEVEL = 801,                 // 提升翎羽等级
        CMD_SPR_ADVANCE_LINGYU_SUIT = 802,                  // 提升翎羽品阶

        CMD_SPR_WING_ZHULING = 810,                         // 请求翅膀注灵
        CMD_SPR_WING_ZHUHUN = 811,                          // 请求翅膀注魂

        CMD_SPR_HYSY_LIANSHA = 818,                         // 幻影寺院连杀信息
        CMD_SPR_HYSY_STOP_LIANSHA = 819,                    // 幻影寺院终结连杀
		CMD_SPR_HYSY_ENQUEUE = 820,                         // 幻影寺院加入自动匹配队列
        CMD_SPR_HYSY_DEQUEUE = 821,                         // 幻影寺院离开自动匹配队列
		CMD_SPR_HYSY_QUEUE_PLAYER_NUM = 822,                // 幻影寺院等待队列玩家数（有效值：0-10）
        CMD_SPR_HYSY_ENTER_NOTIFY = 823,                    // 幻影寺院通知自动匹配成功
        CMD_SPR_HYSY_ENTER_RESPOND = 824,                   // 幻影寺院自动匹配回应，立即开始或暂不进入
        CMD_SPR_HYSY_AWARD = 825,                           // 幻影寺院活动结果奖励信息
        CMD_SPR_HYSY_SCORE_INFO = 826,                      // 幻影寺院通知活动双方得分状态
        CMD_SPR_NOTIFY_TIME_STATE = 827,                    // 通知活动状态和时间(通用)
        CMD_SPR_HYSY_SUCCESS_COUNT = 828,                   // 幻影寺院查询/通知今日获胜次数
        CMD_SPR_HYSY_ADD_SCORE = 829,                       // 幻影寺院通知分数增加

        CMD_SPR_REGION_EVENT = 830,                         // 地图区域事件报告
        CMD_SYNC_TIME_BY_CLIENT = 831,                      // 客户端每2分钟校验时间消息
        CMD_SYNC_TIME_BY_SERVER = 832,                      // 服务器向客户端发送时间消息

        CMD_SPR_GETLUOLANCHENGZHU = 840,                    // 请求罗兰城主基本信息
        CMD_SPR_QUERYADRATIONLANCHENGZHUO = 841,            // 请求罗兰城主崇拜信息
        CMD_SPR_ADRATIONLANCHENGZHU = 842,                  // 罗兰城主崇拜

        CMD_SPR_GET_YUEKA_DATA = 850,                       //月卡信息请求
        CMD_SPR_GET_YUEKA_AWARD = 851,                      //领取月卡奖励请求

        CMD_SECOND_PASSWORD_CHECK_STATE = 860,              //登录时请求账号下所有角色的二级密码
        CMD_SECOND_PASSWORD_SET = 861,                //设置密码
        CMD_SECOND_PASSWORD_VERIFY = 862,              //验证二级密码
        CMD_SECOND_PASSWORD_CANCEL = 863,             // 客户端请求取消二级密码

        CMD_SPR_MARRY_FUBEN = 870,                          //[bing] 情侣副本协议
        CMD_SPR_MARRY_ROSE = 871,                           //[bing] 情侣献花
        CMD_SPR_MARRY_RING = 872,                           //[bing] 婚戒替换
        CMD_SPR_MARRY_MESSAGE = 873,                        //[bing] 爱情宣言更新
        CMD_SPR_MARRY_PARTY_QUERY = 880,                    // 获取婚宴列表
        CMD_SPR_MARRY_PARTY_CREATE = 881,                   // 举行婚宴
        CMD_SPR_MARRY_PARTY_CANCEL = 882,                   // 取消婚宴
        CMD_SPR_MARRY_PARTY_JOIN = 883,                     // 參加婚宴
        CMD_SPR_MARRY_PARTY_JOIN_LIST = 884,                //参加婚宴次数数据

        CMD_SPR_MARRY_INIT = 890,                           //求婚发起
        CMD_SPR_MARRY_REPLY = 891,                          //求婚回复
        CMD_SPR_MARRY_DIVORCE = 892,                        //离婚或离婚回复
        CMD_SPR_MARRY_AUTO_REJECT = 893,                    //自动拒绝求婚
        CMD_SPR_MARRY_NOTIFY = 894,                         //回复求婚离婚通知对方
        CMD_SPR_MARRY_UPDATE = 895,                         //婚姻状态更新
        CMD_SPR_MARRY_SPOUSE_DATA = 896,                    //结婚对象数据

        CMD_SPR_QUERY_JIERI_GIVE_INFO = 920,                //查询节日赠送信息
        CMD_SPR_JIERI_GIVE_TO_OTHER = 921,                  //赠送礼物
        CMD_SPR_GET_JIERI_GIVE_AWARD = 922,                 //节日赠送，领取奖励
        CMD_SPR_QUERY_JIERI_GIVE_KING_INFO = 923,           //查询节日赠送王数据
        CMD_SPR_GET_JIERI_GIVE_KING_AWARD = 924,           //领取节日赠送王奖励
        CMD_SPR_QUERY_JIERI_RECV_KING_INFO = 925,           //查询节日收取王数据
        CMD_SPR_GET_JIERI_RECV_KING_AWARD = 926,            //领取节日收取王奖励
        CMD_DB_EXECUXJIERIFANLI = 927,                      //查询节日通用返利信息

        CMD_SPR_QUERY_LIANXU_CHARGE_INFO = 940,             //查询连续充值活动信息
        CMD_SPR_GET_LIANXU_CHARGE_AWARD = 941,              //领取连续充值活动奖励
        CMD_SPR_QUERY_JIERI_RECV_INFO = 944,                //查询节日收礼信息
        CMD_SPR_GET_JIERI_RECV_AWARD = 945,                 //领取节日收礼奖励
        CMD_SPR_GETINPUT_POINTS_EXCHGINFO = 1500,           //获得充值积分相关数据 
        CMD_SPR_SYNCINPUT_POINTS_ONLY = 1502,               //同步充值点积分

        CMD_SPR_TIANTI_JOIN = 950,  //开始匹配
        CMD_SPR_TIANTI_QUIT = 951, //取消匹配
        CMD_SPR_TIANTI_ENTER = 952, //匹配成功，通知进入活动
        CMD_SPR_TIANTI_AWARD = 953, //结果和奖励信息
        CMD_SPR_TIANTI_DAY_DATA = 954, //角色天梯数据
        CMD_SPR_TIANTI_MONTH_PAIHANG = 955, //获取月段位排行榜.
        CMD_SPR_TIANTI_GET_PAIMING_AWARDS = 956, //领取上月段位排行奖励
        CMD_SPR_ROLE_ATTRIBUTE_VALUE = 968, //通知角色货币变化(当前值和增减量)
        CMD_SPR_TIANTI_GET_LOG = 969, //获取战报列表
        CMD_SPR_EFFECT_HIDE_FLAGS = 970, //(客户端)效果屏蔽选项
     
       	CMD_SPR_TALENT_GET_DATA     = 1000,                 //获取天赋数据
        CMD_SPR_TALENT_ADD_EXP      = 1001,                 //注入经验
        CMD_SPR_TALENT_WASH         = 1002,                 //洗点
        CMD_SPR_TALENT_ADD_EFFECT   = 1003,                 //效果升级

        #region 1100-1199-lt

        CMD_SPR_YONGZHEZHANCHANG_JOIN = 1100, //勇者战场报名
        CMD_SPR_YONGZHEZHANCHANG_ENTER = 1101, //勇者战场进入
        CMD_SPR_YONGZHEZHANCHANG_AWARD = 1102, //勇者战场结束及奖励(通知客户端可以领取)
        CMD_SPR_YONGZHEZHANCHANG_STATE = 1103, //勇者战场报名状态
        CMD_SPR_YONGZHEZHANCHANG_SIDE_SCORE = 1104, //勇者战场分数信息
        CMD_SPR_YONGZHEZHANCHANG_SELF_SCORE = 1105, //勇者战场自己分数增加信息
        CMD_SPR_YONGZHEZHANCHANG_LIANSHA = 1106, //勇者战场连杀信息
        CMD_SPR_YONGZHEZHANCHANG_STOP_LIANSHA = 1107, //勇者战场终结连杀
        CMD_SPR_YONGZHEZHANCHANG_AWARD_GET = 1108, //领取奖励

        CMD_SPR_KUAFU_BOSS_JOIN = 1120, //跨服BOSS报名
        CMD_SPR_KUAFU_BOSS_ENTER = 1121, //跨服BOSS进入
        CMD_SPR_KUAFU_BOSS_DATA = 1122, //跨服BOSS场景数据
        CMD_SPR_KUAFU_BOSS_STATE = 1123, //跨服BOSS报名状态

        // 王者战场相关 所有消息结构模仿勇者战场
        CMD_SPR_KINGOFBATTLE_JOIN = 1180 , //王者战场报名 1
        CMD_SPR_KINGOFBATTLE_ENTER = 1181 , //王者战场进入 1
        CMD_SPR_KINGOFBATTLE_AWARD = 1182 , //王者战场结束及奖励(通知客户端可以领取) 2
        CMD_SPR_KINGOFBATTLE_STATE = 1183 , //王者战场报名状态 1
        CMD_SPR_KINGOFBATTLE_SIDE_SCORE = 1184 , //王者战场分数信息
        CMD_SPR_KINGOFBATTLE_SELF_SCORE = 1185 , //王者战场自己分数增加信息
        CMD_SPR_KINGOFBATTLE_LIANSHA = 1186 , //王者战场连杀信息
        CMD_SPR_KINGOFBATTLE_STOP_LIANSHA = 1187 , //王者战场终结连杀
        CMD_SPR_KINGOFBATTLE_AWARD_GET = 1188 , //领取奖励
        CMD_SPR_KINGOFBATTLE_TELEPORT = 1189 , // 王者战场传送门数据
        CMD_SPR_KINGOFBATTLE_MALL_DATA = 1190 , // 获取王者商店数据
        CMD_SPR_KINGOFBATTLE_MALL_BUY = 1191 , // 王者商店购买
        CMD_SPR_KINGOFBATTLE_MALL_REFRESH = 1192 , // 王者商店刷新

        CMD_SPR_KUAFU_MAP_INFO = 1140, //跨服主线地图线路状态信息
        CMD_SPR_KUAFU_MAP_ENTER = 1141, //跨服主线地图进入

        CMD_SPR_LANGHUNLINGYU_LONGTA_ROLEINFO = 1150,    //龙塔内人数信息列表
        CMD_SPR_LANGHUNLINGYU_QIZHI_OWNERINFO = 1151,    //旗帜拥有者列表
        CMD_SPR_LANGHUNLINGYU_LONGTA_OWNERINFO = 1152,   //龙塔占有者信息
        CMD_SPR_LANGHUNLINGYU_JOIN = 1153,               //报名
        CMD_SPR_LANGHUNLINGYU_DATA = 1154,               //请求玩家自己的狼魂领域数据
        CMD_SPR_LANGHUNLINGYU_CITY_DATA = 1155,          //请求城池占领、进攻信息数据
        CMD_SPR_LANGHUNLINGYU_WORLD_DATA = 1156,         //请求玩家自己的狼魂领域数据
        CMD_SPR_LANGHUNLINGYU_ENTER = 1157,              //进入城池
        CMD_SPR_LANGHUNLINGYU_GET_DAY_AWARD = 1158,      //获取每日奖励
        CMD_SPR_LANGHUNLINGYU_AWARD = 1159,              //服务器推送战斗结果和奖励信息

        CMD_SPR_LANGHUNLINGYU_ADMIRE_DATA = 1160,        //获取当前圣域城主基本信息-膜拜
        CMD_SPR_LANGHUNLINGYU_ADMIRE_HIST = 1161,        //获取历届圣域城主膜拜信息
        CMD_SPR_LANGHUNLINGYU_ADMIRE = 1162,             //膜拜圣域城主

        #endregion 1100-1199-lt


        CMD_SPR_QUERY_JIERI_PLAT_CHARGE_KING = 1300,
        CMD_SPR_MORI_JOIN = 1301, //开始匹配末日审判
        CMD_SPR_MORI_QUIT = 1302, //取消匹配
        CMD_MORI_NTF_ROLE_COUNT = 1303, // 服务器通知客户端队伍人数
        CMD_MORI_NTF_ENTER = 1304, // 服务器通知客户端可以进入末日审判了
        CMD_NTF_MORI_MONSTER_EVENT = 1305, //服务器通知客户端boss事件(出生，死亡)
        CMD_NTF_MORI_COPY_CANCEL = 1306, // 副本取消




        CMD_SPR_ELEMENT_WAR_JOIN = 1010,                         // 元素试炼——开始匹配
        CMD_SPR_ELEMENT_WAR_QUIT = 1011,                         // 元素试炼——取消匹配
        CMD_SPR_ELEMENT_WAR_ENTER = 1012,                        // 元素试炼——匹配成功进入
        CMD_SPR_ELEMENT_WAR_PLAYER_NUM = 1013,                   // 元素试炼——匹配人数变化   
        CMD_SPR_ELEMENT_WAR_SCORE_INFO = 1014,                   // 元素试炼——得分信息
        CMD_SPR_ELEMENT_WAR_AWARD = 1015,                        // 元素试炼——领奖信息
        CMD_SPR_ELEMENT_WAR_CANCEL = 1016,                        // 元素试炼——副本取消

        CMD_SPR_COPY_WOLF_SCORE_INFO = 1025 ,//狼魂要塞——得分信息
        CMD_SPR_COPY_WOLF_AWARD = 1026 ,//狼魂要塞——领奖信息





        CMD_SPR_TASKLIST_DATA = 29900, 
        CMD_SPR_TASKLIST_KEY = 30000,						//服务端发给客戶端的密钥消息 
        CMD_SPR_TASKLIST_NOTIFY = 30001,					//客戶端定时发给服务端的进程列表

        CMD_DB_START_CMD = 10000,//数据库命令
        CMD_DB_UPDATE_POS, CMD_DB_UPDATE_EXPLEVEL, CMD_DB_UPDATE_INTERPOWER,
        CMD_DB_UPDATEMONEY1_CMD, CMD_DB_ADDGOODS_CMD, CMD_DB_UPDATEGOODS_CMD,
        CMD_DB_UPDATETASK_CMD, CMD_DB_UPDATEPKMODE_CMD, CMD_DB_UPDATEPKVAL_CMD, CMD_DB_UPDATEKEYS,
        CMD_DB_UPDATEUSERMONEY_CMD, CMD_DB_UPDATEUSERYINLIANG_CMD, CMD_DB_MOVEGOODS_CMD, CMD_DB_UPDATE_LEFTFIGHTSECS,
        CMD_DB_ROLE_ONLINE, CMD_DB_ROLE_HEART, CMD_DB_ROLE_OFFLINE, CMD_DB_GET_CHATMSGLIST,
        CMD_DB_HORSEON, CMD_DB_HORSEOFF, CMD_DB_PETOUT, CMD_DB_PETIN, CMD_DB_ADDDJPOINT, CMD_DB_UPJINGMAI_LEVEL,
        CMD_DB_REGUSERID, CMD_DB_BANROLENAME, CMD_DB_BANROLECHAT, CMD_DB_GETBANROLECATDICT, CMD_DB_ADDBULLMSG, CMD_DB_REMOVEBULLMSG,
        CMD_DB_GETBULLMSGDICT, CMD_DB_UPDATEONLINETIME, CMD_DB_GAMECONFIGDICT, CMD_DB_GAMECONIFGITEM, CMD_DB_RESETBIGUAN,
        CMD_DB_ADDSKILL, CMD_DB_UPSKILLINFO, CMD_DB_UPDATEJINGMAIEXP, CMD_DB_UPDATEDEFSKILLID, CMD_DB_UPDATEAUTODRINK,
        CMD_DB_UPDATEDAILYTASKDATA, CMD_DB_UPDATEDAILYJINGMAI, CMD_DB_UPDATENUMSKILLID, CMD_DB_UPDATEPBINFO, CMD_DB_UPDATHUODONGINFO,
        CMD_DB_SUBCHONGZHIJIFEN, CMD_DB_USELIPINMA, CMD_DB_UPDATEFUBENDATA, CMD_DB_GETFUBENSEQID, CMD_DB_UPDATEROLEDAILYDATA,
        CMD_DB_UPDATEBUFFERITEM, CMD_DB_UNDELROLENAME, CMD_DB_ADDFUBENHISTDATA, CMD_DB_UPDATELIANZHAN, CMD_DB_UPDATEKILLBOSS, CMD_DB_UPDATEROLESTAT,
        CMD_DB_UPDATEYABIAODATA, CMD_DB_UPDATEYABIAODATASTATE, CMD_DB_UPDATEBATTLENAME, CMD_DB_ADDMALLBUYITEM, CMD_DB_GETLIPINMAINFO,
        CMD_DB_UPDATECZTASKID, CMD_DB_GETTOTALONLINENUM, CMD_DB_UPDATEBATTLENUM, CMD_DB_UPDATEHEROINDEX, CMD_DB_FORCERELOADPAIHANG, CMD_DB_ADDYINPIAOBUYITEM,
        CMD_DB_DELROLENAME, CMD_SPR_QUERYUMBYNAME, CMD_DB_QUERYBHMGRLIST, CMD_DB_UPDATEBANGGONG_CMD, CMD_DB_UPDATEBHTONGQIAN_CMD, CMD_DB_GETBHJUNQILIST,
        CMD_DB_GETBHLINGDIDICT, CMD_DB_UPDATELINGDIFORBH, CMD_DB_GETLEADERROLEIDBYBHID, CMD_DB_ADDBHTONGQIAN_CMD, CMD_DB_ADDQIZHENGEBUYITEM,
        CMD_DB_UPDATEJIEBIAOINFO, CMD_DB_ADDREFRESHQIZHENREC, CMD_DB_CLEARCACHINGROLEIDATA, CMD_DB_ADDMONEYWARNING, CMD_DB_QUERYCHONGZHIMONEY,
        CMD_DB_ADDYINLIANGBUYITEM, CMD_DB_ADDBANGGONGBUYITEM, CMD_DB_SENDUSERMAIL, CMD_DB_GETUSERMAILDATA, CMD_DB_FINDROLEID_BYROLENAME, CMD_DB_QUERYLIMITGOODSUSEDNUM,
        CMD_DB_UPDATELIMITGOODSUSEDNUM, CMD_DB_UPDATEDAILYVIPDATA, CMD_DB_UPDATEDAILYYANGGONGBKJIFENDATA, CMD_DB_UPDATESINGLETIMEAWARDFLAG, CMD_DB_ADDSHENGXIAOGUESSHIST,
        CMD_DB_UPDATEUSERGOLD_CMD, CMD_DB_ADDGOLDBUYITEM, CMD_DB_UPDATEROLEBAGNUM, CMD_DB_SETLINGDIWARREQUEST, CMD_DB_UPDATEGOODSLIMIT, CMD_DB_UPDATEROLEPARAM,
        CMD_DB_ADDQIANGGOUBUYITEM, CMD_DB_ADDQIANGGOUITEM, CMD_DB_QUERYCURRENTQIANGGOUITEM, CMD_DB_QUERYQIANGGOUBUYITEMS, CMD_DB_UPDATEQIANGGOUTIMEOVER,
        CMD_DB_GETBANGHUIMINIDATA, CMD_DB_ADDBUYITEMFROMNPC, CMD_DB_ADDZAJINDANHISTORY, CMD_DB_QUERYQIANGGOUBUYITEMINFO, CMD_DB_QUERYFIRSTCHONGZHIBYUSERID,
        CMD_DB_QUERYKAIFUONLINEAWARDROLEID, CMD_DB_ADDKAIFUONLINEAWARD, CMD_DB_ADDGIVEUSERMONEYITEM, CMD_DB_QUERYKAIFUONLINEAWARDLIST,
        CMD_DB_ADDEXCHANGE1ITEM, CMD_DB_ADDEXCHANGE2ITEM, CMD_DB_ADDEXCHANGE3ITEM, CMD_DB_ADDFALLGOODSITEM, CMD_DB_UPDATEROLEPROPS, CMD_DB_QUERYTODAYCHONGZHIMONEY,
        CMD_DB_QUERYDAYCHONGZHIBYUSERID, CMD_DB_CLEARALLCACHINGROLEDATA,
        CMD_DB_QUERYXINGYUNORYUEDUCHOUJIANGINFO,    // GS-DB 询问幸运或月度抽奖信息 [7/17/2013 LiaoWei]
        CMD_DB_EXECUXINGYUNORYUEDUCHOUJIANGINFO,    // GS-DB 更新幸运或月度抽奖信息 [7/17/2013 LiaoWei]
        CMD_DB_ADDYUEDUCHOUJIANGHISTORY,            // GS-DB 增加月度抽奖历史信息 [7/23/2013 LiaoWei]
        CMD_DB_EXECUTECHANGEOCCUPATION,             // GS-DB 转职操作  [9/28/2013 LiaoWei]
        CMD_DB_QUERYBLOODCASTLEENTERCOUNT,          // GS-DB 请求血色堡垒进入次数[11/6/2013 LiaoWei]
        CMD_DB_UPDATEBLOODCASTLEENTERCOUNT,         // GS-DB 更新血色堡垒进入次数[11/6/2013 LiaoWei]
        CMD_DB_QUERYFUBENHISINFO,                   // GS-DB 请求副本历史信息 [11/16/2013 LiaoWei] 
        CMD_DB_CLEANDATAWHENFRESHPLAYERLOGOUT,      // GS-DB 在新手阶段掉线处理 [12/2/2013 LiaoWei]
        CMD_DB_FINISHFRESHPLAYERSTATUS,             // GS-DB 结束新手阶段 [12/2/2013 LiaoWei]
        CMD_DB_EXECUTECHANGETASKSTARLEVEL,          // GS-DB 改变任务星级等级[12/3/2013 LiaoWei]
        CMD_DB_EXECUTEUPDATEROLESOMEINFO,           // GS-DB 更新角色的一些信息 [12/17/2013 LiaoWei]
        CMD_DB_QUERYDAYACTIVITYTOTALPOINT,          // GS-DB 请求日常活动最高积分信息 [12/24/2013 LiaoWei]
        CMD_DB_QUERYDAYACTIVITYSELFPOINT,           // GS-DB 请求自己的日常活动积分信息 [12/24/2013 LiaoWei]
        CMD_DB_UPDATEDAYACTIVITYSELFPOINT,          // GS-DB 更新自己的日常活动积分信息 [12/24/2013 LiaoWei]
        CMD_DB_QUERYEVERYDAYONLINEAWARDGIFTINFO,    // GS-DB 请求每日在线奖励信息 [1/12/2014 LiaoWei]
        CMD_DB_ADD_ZHANMENGSHIJIAN,                 // GS-DB 请求请求添加战盟事件 [3/14/2014 JinJieLong]
        CMD_DB_ZHANMENGSHIJIAN_DETAIL,              // GS-DB 请求战盟事件详情 [3/14/2014 JinJieLong]
        CMD_DB_JINGJICHANG_GET_DATA,                // GS-DB 请求获取玩家竞技场数据 [3/21/2014 JinJieLong]
        CMD_DB_JINGJICHANG_GET_CHALLENGE_DATA,      // GS-DB 请求获取竞技场被挑战者mini数据 [3/21/2014 JinJieLong]
        CMD_DB_JINGJICHANG_CREATE_DATA,             // GS-DB 请求创建竞技场数据 [3/22/2014 JinJieLong]
        CMD_DB_JINGJICHANG_REQUEST_CHALLENGE,       // GS-DB 竞技场请求挑战 [3/22/2014 JinJieLong]
        CMD_DB_JINGJICHANG_CHALLENGE_END,           // GS-DB 竞技场挑战结束 [3/22/2014 JinJieLong]
        CMD_DB_JINGJICHANG_SAVE_DATA,               // GS-DB 保存竞技场数据 [3/22/2014 JinJieLong]
        CMD_DB_JINGJICHANG_ZHANBAO_DATA,            // GS-DB 获取竞技场战报数据 [3/22/2014 JinJieLong]
        CMD_DB_JINGJICHANG_REMOVE_CD,               // GS-DB 消除挑战CD [3/25/2014 JinJieLong]
        CMD_DB_JINGJICHANG_GET_RANKING_AND_NEXTREWARDTIME,// GS-DB 获取排名和下次领取奖励时间 [3/25/2014 JinJieLong]
        CMD_DB_JINGJICHANG_UPDATE_NEXTREWARDTIME,   // GS-DB  更新下次领取竞技场排行榜奖励时间 [3/25/2014 JinJieLong]
        CMD_DB_ADD_BAITANLOG,                       // GS-DB 请求请求添加摆摊日志
        CMD_DB_UPDATEPUSHMESSAGEINFO,               // GS-DB 更新推送信息 [4/23/2014 LiaoWei]
        CMD_DB_QUERYPUSHMESSAGEUSERLIST,            // GS-DB 请求要推送的玩家列表 [4/23/2014 LiaoWei]
        CMD_DB_ADDWING,                             // GS-DB 请求得到第一个翅膀[4/30/2014, liuhuicheng]
        CMD_DB_MODWING,                             // GS-DB 请求修改翅膀[4/30/2014, liuhuicheng]
        CMD_DB_REFERPICTUREJUDGE,                   // GS-DB 提交图鉴信息 [5/18/2014 LiaoWei]
        CMD_DB_QUERYMOJINGEXCHANGEINFO,             // GS-DB 请求绑定钻石兑换信息 [5/21/2014 LiaoWei]
        CMD_DB_UPDATEMOJINGEXCHANGEINFO,            // GS-DB 更新绑定钻石兑换信息 [5/21/2014 LiaoWei]
        CMD_DB_MODIFY_WANMOTA,                      // GS-DB 修改万魔塔表数据 [6/6/2014 ChenXiaojun]
        CMD_DB_GET_WANMOTA_DETAIL,                  // GS-DB 获取万魔塔信息 [6/6/2014 ChenXiaojun]
        CMD_DB_QUERY_REPAYACTIVEINFO,               // GS-DB 查询回馈活动信息
        CMD_DB_GET_REPAYACTIVEAWARD,                // GS-DB 获取回馈活动奖励
        CMD_DB_UPDATE_ACCOUNT_ACTIVE,               // GS-DB 更新帐户活跃信息  [7/9/2014 ChenXiaojun]
        CMD_DB_QUERY_GETOLDRESINFO,                 // GS-DB 查询资源找回信息 [7/11/2014 gwz]
        CMD_DB_UPDATE_OLDRESOURCE,                  // GS-DB 资源找回，领取资源 [7/11/2014 gwz]
        CMD_DB_UPDATEGOODS_CMD2,                    // GS-DB 更新物品扩展信息(装备洗练等)
        CMD_DB_UPDATESTARCONSTELLATION,             // GS-DB 激活星座更新星座信息 [8/1/2014 LiaoWei]
        CMD_DB_SAVECONSUMELOG,                      // GS-DB 保存钻石消费信息 [8/19/2014 gwz]
        CMD_DB_QUERYVIPLEVELAWARDFLAG,              // GS-DB 玩家领取VIP等级奖励 [8/21/2014 LiaoWei]
        CMD_DB_UPDATEVIPLEVELAWARDFLAG,             // GS-DB 玩家更新VIP等级奖励标记信息 [8/21/2014 LiaoWei]
        CMD_DB_UPDATEFIRSTCHARGE,                   // GS-DB 玩家更新首充信息 [9/16/2014 gwz]


        CMD_DB_GET_SERVERLIST = 11000,
        CMD_DB_ONLINE_SERVERHEART,
        CMD_NAME_REGISTERNAME = 12000,             //注册名字到名字服务器
        CMD_SPR_GM_SET_MAIN_TASK = 13000,          //GM命令设置任务

        CMD_SPR_KF_SWITCH_SERVER = 14000,           //跨服_通知客户端切换服务器(包含跨服登录Token)
        CMD_LOGDB_ADD_ITEM_LOG = 20000,             // 向日志数据库服务器添加物品操作日志

        // 老玩家召回系统
        //CMD_SPR_RETURN_RECRUIT_INFO = 900,                // 当前推荐人信息——获取信息
        //CMD_SPR_RETURN_RECRUIT_SET = 901,                 // 当前推荐人信息——设置
        //CMD_SPR_RETURN_AWARD_INFO = 902,                  // 回归礼包——获取信息
        //CMD_SPR_RETURN_AWARD_SET = 903,                   // 回归礼包——领取
        //CMD_SPR_RETURN_CHECK_INFO = 904,                  // 签到信息——获取信息
        //CMD_SPR_RETURN_CHECK_SET = 905,                   // 签到信息——签到
        //CMD_SPR_RETURN_RECRUIT_AWARD_INFO = 906,          // 召回奖励——获取信息
        //CMD_SPR_RETURN_RECRUIT_AWARD_SET = 907,           // 召回奖励——设置
        //CMD_SPR_RETURN_RECRUIT_EXTRA_AWARD = 908,         // 召回奖励——额外奖励领取
        CMD_SPR_RETURN_DATA = 900 ,                  // (获取召回活动信息) 新1655
        CMD_SPR_RETURN_CHECK = 901 ,                 // (校验回归资格)
        CMD_SPR_RETURN_AWARD = 902 ,                 // (领取奖励)

        // 守护雕像
        CMD_SPR_QUERY_GUARD_POINT_RECOVER = 930,  // 查询守护点信息
        CMD_SPR_GUARD_POINT_RECOVER = 931,        // 回收守护点
        CMD_SPR_QUERY_GUARD_STATUE_INFO = 932,    // 查询守护雕像信息
        CMD_SPR_GUARD_STATUE_LEVEL_UP = 933,      // 升级守护雕像
        CMD_SPR_GUARD_STATUE_SUIT_UP = 934,       // 升阶守护雕像
        CMD_SPR_MOD_GUARD_SOUL_EQUIP = 935,       // 穿戴、卸下守护之灵


        //改名服务 @wanggc
        CMD_NTF_EACH_ROLE_ALLOW_CHANGE_NAME = 14002,
        CMD_SPR_CHANGE_NAME = 14001,                         // 客户端向服务器端发送的角色请求改名
        CMD_NTF_CANNOT_JOIN_KUAFU_FU_BEN_END_TICKS = 14003, //服务器通知客户端更新禁止参与跨服副本的结束时间, DateTime.Now.Ticks
        CMD_PLEASE_TELL_ME = 14004,

        CMD_SPR_CHANGE_BANGHUI_NAME = 14006, // 更改帮会名字
        CMD_NTF_BANGHUI_CHANGE_NAME = 1315, // 通知帮会改名客户端访问参数

        //圣物系统 @wanggc
        CMD_DB_UPDATE_HOLYITEM = 10206,                    //  生物升级
        CMD_SPR_HOLYITEM_DATA = 1200,             // 玩家登陆时返回整个圣物字典 一共4个圣物和所有部件信息
        CMD_SPR_HOLYITEM_PART_DATA = 1201,        // 当部件信息改变时发送改变的圣物部件信息(比如碎片数量改变 或者圣物升级)





        CMD_SPR_MERLIN_QUERY = 981,    // 客户端请求梅林魔法书数据 [XSea 2015/6/23]
        CMD_SPR_MERLIN_STAR_UP = 982, // 客户端请求梅林魔法书升星 [XSea 2015/6/23]
        CMD_SPR_MERLIN_LEVEL_UP = 983, // 客户端请求梅林魔法书升阶 [XSea 2015/6/24]
        CMD_SPR_MERLIN_SECRET_ATTR_UPDATE = 984,    // 客户端请求擦拭梅林魔法书秘语 [XSea 2015/6/25]
        CMD_SPR_MERLIN_SECRET_ATTR_REPLACE = 985,    // 客户端请求替换梅林魔法书秘语 [XSea 2015/6/25]
        CMD_SPR_MERLIN_SECRET_ATTR_NOT_REPLACE = 986,    // 客户端请求放弃替换梅林魔法书秘语 [XSea 2015/6/25]

        CMD_SPR_GET_FASHION_SLIST = 946, // 时装
        CMD_SPR_LOGIN_WAITING_INFO = 971,// 通知客户端排队信息

        // 荧光宝石
        CMD_SPR_FLUORESCENT_GEM_RESET_BAG = 991,    // 整理荧光宝石背包
        CMD_SPR_FLUORESCENT_GEM_EQUIP = 992,        // 镶嵌荧光宝石
        CMD_SPR_FLUORESCENT_GEM_UN_EQUIP = 993,     // 卸下荧光宝石
        CMD_SPR_FLUORESCENT_GEM_LEVEL_UP = 994,     // 升级荧光宝石
        CMD_SPR_FLUORESCENT_GEM_DIG = 995,          // 挖掘荧光宝石
        CMD_SPR_FLUORESCENT_GEM_RESOLVE = 996,      // 分解荧光宝石
        CMD_SPR_FLUORESCENT_GEM_EQUIP_CHANGES = 997, // 通知客户端荧光宝石装备栏变动

        // 推广系统
        CMD_SPR_SPREAD_SIGN = 1017,         // 成为推广员
        CMD_SPR_SPREAD_AWARD = 1018,        // 领取奖励
        CMD_SPR_SPREAD_ROLE = 1019,         // 填写推荐人
        CMD_SPR_SPREAD_CODE_GET = 1020,     // 获取验证码
        CMD_SPR_SPREAD_CODE_VARIFY = 1021,  // 确认验证码
        CMD_SPR_SPREAD_INFO = 1022,         // 推广信息

        //领地
        CMD_SPR_BUILD_GET_LIST = 1550,                          // 获得领地所有信息
        CMD_SPR_BUILD_EXCUTE = 1551,	                        // 执行开发任务
        CMD_SPR_BUILD_FINISH = 1552,                            // 一键完成开发任务
        CMD_SPR_BUILD_REFRESH = 1553,                           // 刷新开发任务
        CMD_SPR_BUILD_GET_ALLLEVEL_AWARD = 1554,                // 获取总等级奖励
        CMD_SPR_BUILD_GET_AWARD = 1555,                         // 获取开发奖励
        CMD_SPR_BUILD_OPEN_QUEUE = 1556,                        // 开启收费开发队列
        CMD_SPR_BUILD_GET_QUEUE = 1557,
        // 获得开发队列数据
        CMD_SPR_BUILD_GET_STATE = 1558,                         //客户端获取建筑状态
        CMD_SPR_BUILD_GET_ALLLEVEL_AWARD_STATE = 1559,         // 同步总等级奖励领取状态
        CMD_SPR_BUILD_SYNC_SINGLE = 1560,                      // 同步单个建筑物数据


        //警告提示信息 @wangnl
        CMD_SPR_WARN_INFO = 1004,

        CMD_DB_ERR_RETURN = 30767, // MAX 任何消息定义请不要超过这个值

        CMD_SPR_GETWEEKEND_INPUT_DATA = 1501,         //获得周末充值相关数据

        // 七日狂欢活动

        CMD_SPR_SEVEN_DAY_ACT_QUERY = 1310, // 查询七日活动信息  客户端访问参数：角色ID (roleid)
        CMD_SPR_SEVEN_DAY_ACT_GET_AWARD = 1311, // 领取七日活动奖励 (七日登录，七日充值，七日目标)   客户端访问参数：roleid:actType:id	角色id：活动类型：领取的那一项的ID

        CMD_SPR_SEVEN_DAY_ACT_QIANG_GOU = 1312, // 抢购物品 (七日抢购)          客户端访问参数：roleid:id:cnt	角色id：领取的那一项的ID：抢购数量

        CMD_SPR_TODAY_DATA = 1030,              //每日专项——获取数据
        CMD_SPR_TODAY_AWARD = 1031,             //每日专项——领取奖励
        CMD_SYNC_CHANGE_DAY_SERVER = 833,       //服务器通知客户端跨天了      
        //藏宝秘境
        CMD_SPR_ONEPIECE_GET_INFO = 1600,               // c2s 获取藏宝秘境相关信息
        CMD_SPR_ONEPIECE_ROLL,                          // c2s 扔骰子
        CMD_SPR_ONEPIECE_TRIGGER_EVENT,                 // c2s 客户端触发事件 
        CMD_SPR_ONEPIECE_SYNC_EVENT,                    // s2c 服务器向客户端同步当前事件信息
        CMD_SPR_ONEPIECE_MOVE,                          // c2s 请求移动
        CMD_SPR_ONEPIECE_ROLL_MIRACLE,                  // c2s 扔奇迹骰子
        CMD_SPR_ONEPIECE_DICE_BUY,                      // c2s 购买骰子
        CMD_SPR_ONEPIECE_SYNC_DICE,                      // 同步骰子数
        // 魂石
        CMD_SPR_SOUL_STONE_QUERY_GET = 1320,    //查询魂石随机信息
        CMD_SPR_SOUL_STONE_GET = 1321,          //获取魂石
        CMD_SPR_SOUL_STONE_LVL_UP = 1322,       //魂石升级
        CMD_SPR_SOUL_STONE_MOD_EQUIP = 1323,    //穿戴或卸下
        CMD_SPR_SOUL_STONE_RESET_BAG = 1324,    //整理魂石背包

        //成长基金   
        CMD_SPR_FUND_INFO = 1032,   // 获取基金信息
        CMD_SPR_FUND_BUY = 1033,    // 购买基金
        CMD_SPR_FUND_AWARD = 1034,    // 领取奖励

        CMD_SPR_SET_FUNCTION_OPEN = 1330, // 设置二态功能的开启或关闭
        //服务器通知客户端退出客户端 
        CMD_NTF_MAGIC_CRASH_UNITY = 14010,

        //时装隐藏功能增加3个消息，罗兰城主，PKKing，竞技场人物雕像信息采用保存的数据，不实时更新，与原有消息进行区分，服务器返回消息结构不变、
        CMD_SPR_JINGJICHANG_GET_ROLE_LOOKS = 1340,   // 竞技场排行界面中查看角色外貌
        CMD_SPR_PKKING_GET_ROLE_LOOKS = 1341, // 查看PKKing角色
        CMD_SPR_LUOLANKING_GET_ROLE_LOOKS = 1342, // 查看罗兰城主

        //众神争霸
        CMD_SPR_ZHENGBA_GET_MAIN_INFO = 1350, //获取主信息
        CMD_SPR_ZHENGBA_GET_ALL_PK_LOG = 1351, //查看全部战报
        CMD_SPR_ZHENGBA_GET_ALL_PK_STATE = 1352, //查看全部参赛
        CMD_SPR_ZHENGBA_GET_16_PK_STATE = 1353, //获取16强中的两两pk状态
        CMD_SPR_ZHENGBA_SUPPORT = 1354,             // 赞、贬、押注
      //  CMD_SPR_ZHENGBA_YA_ZHU = 1355,              // 众神争霸 --- 押注
        CMD_NTF_ZHENGBA_CAN_ENTER = 1356, //服务器通知客户端可以进入
        CMD_SPR_ZHENGBA_ENTER = 1357,               //进入
        CMD_NTF_ZHENGBA_PK_RESULT = 1358,           // 众神争霸 --- pk结果
        CMD_SPR_ZHENGBA_GET_MINI_STATE = 1359,   //// 获取活动mini进度
        CMD_SPR_ZHENGBA_QUERY_JOIN_HINT = 1360,      //是否提示参与框
        //精灵技能
        CMD_SPR_PET_SKILL_UP = 1037,//宠物技能槽提升
        CMD_SPR_PET_SKILL_AWAKE = 1038,// 宠物技能领悟
        CMD_SPR_PET_SKILL_AWAKE_COST = 1039, //宠物技能领悟消耗灵晶数量
         //账号绑定
        CMD_SPR_ACTIVATE_INFO = 1040,//1、	获取信息
        CMD_SPR_ACTIVATE_AWARD = 1041,//2、	领取奖励
 		//专享活动
        CMD_SPR_SPECIALACTIVITY_GETXMLDATA = 1510,          // 获取专享活动xml配置文件
        CMD_SPR_SPECIALACTIVITY_QUERY = 1511,               // 查询专享活动数据
        CMD_SPR_SPECIALACTIVITY_FETCHAWARD = 1512,          // 领取专享活动奖励   

        //战盟神殿
        CMD_SPR_UNION_PALACE_DATA = 1035,   //  获取战盟神殿信息
        CMD_SPR_UNION_PALACE_UP = 1036,     // 守护提升
        //亲加视频
        CMD_SPR_VIDEO_OPEN =1700,       //获取登陆视频数据


        
        
        CMD_SPR_TAROT_UPORINIT = 1701,// 1、	塔罗牌——塔罗牌激活
        CMD_SPR_SET_TAROTPOS = 1702,   //  1、	塔罗牌——塔罗牌佩戴
        CMD_SPR_USE_TAROTKINGPRIVILEGE = 1703,   //塔罗牌——使用国王特权
        CMD_SPR_TAROT_DATA = 1704, //   塔罗牌——发送塔罗牌数据

        CMD_SPR_FASHION_FORGE = 1610,                   // 时装强化
        CMD_SPR_FASHION_ACTIVE = 1611,                  // 时装激活


        #region 战盟外交相关消息
        CMD_SPR_UNION_ALLY_REQUEST = 1042,      //发起战盟结盟请求
        CMD_SPR_UNION_ALLY_CANCEL = 1043,       //取消战盟结盟请求
        CMD_SPR_UNION_ALLY_REMOVE = 1044,      //解除结盟
        CMD_SPR_UNION_ALLY_AGREE = 1045,         //同意、拒绝结盟
        CMD_SPR_UNION_ALLY_DATA = 1046,          //结盟数据，我的盟友数据、结盟请求数据，合在一起
        CMD_SPR_UNION_ALLY_LOG = 1047,           //结盟请求日志数据
        CMD_SPR_UNION_ALLY_NUM = 1048,         //刷新盟友请求界面数据
        #endregion 战盟外交相关消息
        //夫妻竞技场
        CMD_COUPLE_ARENA_GET_MAIN_DATA = 1370,   //注：此消息用于客户端打开主界面时，查询信息

        /* 
         *  注：客户端打开主界面时，注册状态关注。关闭主界面时，取消状态关注。
            该消息是为了保证客户端一直打开主界面的时候，配偶状态变更了，服务器能够主动推送给客户端，这样客户端无须重新打开主界面。
            打开主界面时，一定要先发送CMD_COUPLE_ARENA_GET_MAIN_DATA，在发送本消息，保证客户端收到本消息的回复时，已经收到了主界面信息。
        */
        CMD_COUPLE_ARENA_REG_STATE_WATCHER = 1380,
        CMD_COUPLE_ARENA_GET_ZHAN_BAO = 1371,    //战报
        CMD_COUPLE_ARENA_GET_PAI_HANG = 1372,   //排行榜
        CMD_COUPLE_ARENA_SET_READY = 1373,      //设置准备状态
        CMD_COUPLE_ARENA_SINGLE_JOIN = 1374,    //单人匹配

        /*
         注：无论是单人匹配还是双人匹配，客户端均通过此消息主动请求取消匹配。
	     注：双人匹配中，如果夫妻一方主动取消匹配，那么会通过此消息主动通知配偶，配偶收到此消息后要结束倒计时匹配界面。
         */
        CMD_COUPLE_ARENA_QUIT = 1375,        // 取消匹配
        CMD_COUPLE_ARENA_NTF_CAN_ENTER = 1376,  //单向消息，服务器主动通知客户端可以进入对战
        CMD_COUPLE_ARENA_ENTER = 1377,   //  进入或者取消
        CMD_COUPLE_ARENA_NTF_PK_RESULT = 1378,   //单向消息，服务器通知战斗结果
        CMD_COUPLE_ARENA_NTF_COUPLE_STATE = 1379,   //单向消息，服务器通知状态变更
        CMD_COUPLE_ARENA_NTF_BUFF_HOLDER = 1381,   //单向消息，通知buff持有信息

        #region 夫妻祝福榜

        CMD_COUPLE_WISH_GET_MAIN_DATA = 1390,   // 注：此消息用于客户端打开主界面时，查询信息
        CMD_COUPLE_WISH_GET_WISH_RECORD = 1391,   // 点击祝福记录按钮
        CMD_COUPLE_WISH_WISH_OTHER_ROLE = 1392,    //请求祝福他人
        CMD_COUPLE_WISH_NTF_WISH_EFFECT = 1393,    //单向消息，服务器通知客户端祝福特效
        CMD_COUPLE_WISH_GET_ADMIRE_DATA = 1394,    //客户端查看情侣雕像数据
        CMD_COUPLE_WISH_ADMIRE_STATUE = 1395,    // 客户端请求膜拜雕像
        CMD_COUPLE_WISH_GET_PARTY_DATA = 1396,   // 客户端查看宴会数据
        CMD_COUPLE_WISH_JOIN_PARTY = 1397,    //  客户端点击参加宴会

        #endregion 夫妻祝福榜

        CMD_SPR_TALENT_OTHER = 999,         //获取天赋数据——他人

        CMD_SPR_GETATTRIBALL = 30100,   // 获取装备二级属性
    };
}
